
/* Drop Tables */

DROP TABLE CIP_ATTACHFILE CASCADE CONSTRAINTS;
DROP TABLE CIP_AUTHORITY_MEMBER CASCADE CONSTRAINTS;
DROP TABLE CIP_MENU_AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE CIP_AUTHORITY CASCADE CONSTRAINTS;
DROP TABLE CIP_COMMON_CODE CASCADE CONSTRAINTS;
DROP TABLE CIP_MEMBER CASCADE CONSTRAINTS;
DROP TABLE CIP_MENU CASCADE CONSTRAINTS;
DROP TABLE CIP_MULTI_BOARD CASCADE CONSTRAINTS;
DROP TABLE CIP_ORGANIZATION CASCADE CONSTRAINTS;




/* Create Tables */

-- 파일 정보
CREATE TABLE CIP_ATTACHFILE
(
	-- 첨부파일 일련번호
	ATTACHFILE_SEQ varchar2(40) NOT NULL,
	-- 원본레코드 UNIQUE SEQ
	SOURCE_UNIQUE_SEQ varchar2(40) NOT NULL,
	-- 첨부파일 유형
	ATTACHFILE_TYPE varchar2(40),
	-- 원본 파일명
	ORGINALFILE_NAME varchar2(200) NOT NULL,
	-- 첨부 파일명
	PHYSICALFILE_NAME varchar2(200) NOT NULL,
	-- 썸네일 첨부파일명
	THUMBNAIL_NAME varchar2(500),
	-- 첨부파일 저장경로
	ATTACHFILE_PATH varchar2(500),
	-- 첨부파일 크기
	ATTACHFILE_SIZE number,
	-- 파일 높이
	ATTACHFILE_HEIGHT number,
	-- 파일 폭
	ATTACHFILE_WIDTH number,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (ATTACHFILE_SEQ)
);


-- 권한 종류
CREATE TABLE CIP_AUTHORITY
(
	-- 권한 코드
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 명칭
	NAME varchar2(1000) NOT NULL,
	-- 코드설명
	DESCRIPTION varchar2(1000),
	-- 사용 여부
	USE_YN varchar2(40) NOT NULL,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (AUTHORITY_ID)
);


-- 사용자별 권한들
CREATE TABLE CIP_AUTHORITY_MEMBER
(
	-- 권한 코드
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 회원_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	UNIQUE (AUTHORITY_ID, MEMBER_SEQ)
);


-- 공통코드
CREATE TABLE CIP_COMMON_CODE
(
	-- 공통 코드_ID
	COMMON_CODE_ID varchar2(40) NOT NULL,
	-- 명칭
	NAME varchar2(1000) NOT NULL,
	-- 정렬순서
	ORDER_NUMBER number,
	-- 속성_1
	ATTRIBUTION_1 varchar2(60),
	-- 속성_2
	ATTRIBUTION_2 varchar2(60),
	-- 코드설명
	DESCRIPTION varchar2(1000),
	-- 초기 시스템 코드 여부
	SYSTEM_CODE_YN varchar2(40) DEFAULT 'N' NOT NULL,
	-- 사용 여부
	USE_YN varchar2(40) NOT NULL,
	-- 상위 공통 코드 ID
	PARENT_COMMON_CODE_ID varchar2(40),
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (COMMON_CODE_ID)
);


-- 회원정보
CREATE TABLE CIP_MEMBER
(
	-- 회원_SEQ
	MEMBER_SEQ varchar2(40) NOT NULL,
	-- 회원 ID
	MEMBER_ID varchar2(50) NOT NULL,
	-- 암호
	PASSWORD varchar2(100) NOT NULL,
	-- 암호화된 암호
	CRYPT_PASSWORD varchar2(100),
	-- 명칭
	NAME varchar2(1000) NOT NULL,
	-- EMAIL
	EMAIL varchar2(1000),
	-- 휴대폰번호
	CELLPHONE varchar2(20),
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	-- 조직 일련번호
	ORGANIZATION_SEQ varchar2(50) NOT NULL,
	PRIMARY KEY (MEMBER_SEQ)
);


-- 메뉴 마스터 정보
CREATE TABLE CIP_MENU
(
	-- 메뉴 코드 SEQ
	MENU_SEQ varchar2(40) NOT NULL,
	-- 명칭
	NAME varchar2(1000) NOT NULL,
	-- 정렬순서
	ORDER_NUMBER number DEFAULT 1 NOT NULL,
	-- 메뉴 주소
	MENU_URI varchar2(500),
	-- 사용 여부
	USE_YN varchar2(40),
	-- 상위 메뉴 코드 SEQ
	PARENT_MENU_SEQ varchar2(40),
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	PRIMARY KEY (MENU_SEQ)
);


-- 메뉴 따른 권한
CREATE TABLE CIP_MENU_AUTHORITY
(
	-- 권한 코드
	AUTHORITY_ID varchar2(40) NOT NULL,
	-- 메뉴 코드 SEQ
	MENU_SEQ varchar2(40) NOT NULL,
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	UNIQUE (AUTHORITY_ID, MENU_SEQ)
);


-- 멀티게시판
CREATE TABLE CIP_MULTI_BOARD
(
	-- 게시물 일련번호
	MULTI_BOARD_SEQ varchar2(40) NOT NULL,
	-- 제목
	TITLE varchar2(4000),
	-- 내용/댓글
	CONTENT varchar2(4000) NOT NULL,
	-- 시작일시 (공지 등)
	START_DATE varchar2(20),
	-- 종료일시 (공지 등)
	END_DATE varchar2(20),
	-- 등록자SEQ
	REGISTER_SEQ varchar2(50) NOT NULL,
	-- 등록일자
	REGISTRY_DATE varchar2(20) NOT NULL,
	-- 수정자_SEQ
	MODIFIER_SEQ varchar2(40) NOT NULL,
	-- 수정일자
	MODIFY_DATE varchar2(20) NOT NULL,
	-- 상위 게시물 일련번호
	PARENT_MULTI_BOARD_SEQ varchar2(40),
	CONSTRAINT PK_MULTI_BOARD PRIMARY KEY (MULTI_BOARD_SEQ)
);


-- 그룹/조직/부서 구조도
CREATE TABLE CIP_ORGANIZATION
(
	-- 조직 일련번호
	ORGANIZATION_SEQ varchar2(50) NOT NULL,
	-- 명칭
	NAME varchar2(1000) NOT NULL,
	-- 대표 전화번호
	TELEPHONE varchar2(40),
	-- 정렬순서
	ORDER_NUMBER number,
	-- 상위 조직 일련번호
	PARENT_ORGANIZATION_SEQ varchar2(50),
	CONSTRAINT PK_ORGANIZATION PRIMARY KEY (ORGANIZATION_SEQ)
);



/* Create Foreign Keys */

ALTER TABLE CIP_AUTHORITY_MEMBER
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES CIP_AUTHORITY (AUTHORITY_ID)
;


ALTER TABLE CIP_MENU_AUTHORITY
	ADD FOREIGN KEY (AUTHORITY_ID)
	REFERENCES CIP_AUTHORITY (AUTHORITY_ID)
;


ALTER TABLE CIP_COMMON_CODE
	ADD FOREIGN KEY (PARENT_COMMON_CODE_ID)
	REFERENCES CIP_COMMON_CODE (COMMON_CODE_ID)
;


ALTER TABLE CIP_AUTHORITY_MEMBER
	ADD FOREIGN KEY (MEMBER_SEQ)
	REFERENCES CIP_MEMBER (MEMBER_SEQ)
;


ALTER TABLE CIP_MENU
	ADD FOREIGN KEY (PARENT_MENU_SEQ)
	REFERENCES CIP_MENU (MENU_SEQ)
;


ALTER TABLE CIP_MENU_AUTHORITY
	ADD FOREIGN KEY (MENU_SEQ)
	REFERENCES CIP_MENU (MENU_SEQ)
;


ALTER TABLE CIP_MULTI_BOARD
	ADD FOREIGN KEY (PARENT_MULTI_BOARD_SEQ)
	REFERENCES CIP_MULTI_BOARD (MULTI_BOARD_SEQ)
;


ALTER TABLE CIP_MEMBER
	ADD FOREIGN KEY (ORGANIZATION_SEQ)
	REFERENCES CIP_ORGANIZATION (ORGANIZATION_SEQ)
;


ALTER TABLE CIP_ORGANIZATION
	ADD FOREIGN KEY (PARENT_ORGANIZATION_SEQ)
	REFERENCES CIP_ORGANIZATION (ORGANIZATION_SEQ)
;



/* Comments */

COMMENT ON TABLE CIP_ATTACHFILE IS '파일 정보';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_SEQ IS '첨부파일 일련번호';
COMMENT ON COLUMN CIP_ATTACHFILE.SOURCE_UNIQUE_SEQ IS '원본레코드 UNIQUE SEQ';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_TYPE IS '첨부파일 유형';
COMMENT ON COLUMN CIP_ATTACHFILE.ORGINALFILE_NAME IS '원본 파일명';
COMMENT ON COLUMN CIP_ATTACHFILE.PHYSICALFILE_NAME IS '첨부 파일명';
COMMENT ON COLUMN CIP_ATTACHFILE.THUMBNAIL_NAME IS '썸네일 첨부파일명';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_PATH IS '첨부파일 저장경로';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_SIZE IS '첨부파일 크기';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_HEIGHT IS '파일 높이';
COMMENT ON COLUMN CIP_ATTACHFILE.ATTACHFILE_WIDTH IS '파일 폭';
COMMENT ON COLUMN CIP_ATTACHFILE.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN CIP_ATTACHFILE.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN CIP_ATTACHFILE.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN CIP_ATTACHFILE.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE CIP_AUTHORITY IS '권한 종류';
COMMENT ON COLUMN CIP_AUTHORITY.AUTHORITY_ID IS '권한 코드';
COMMENT ON COLUMN CIP_AUTHORITY.NAME IS '명칭';
COMMENT ON COLUMN CIP_AUTHORITY.DESCRIPTION IS '코드설명';
COMMENT ON COLUMN CIP_AUTHORITY.USE_YN IS '사용 여부';
COMMENT ON COLUMN CIP_AUTHORITY.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN CIP_AUTHORITY.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN CIP_AUTHORITY.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN CIP_AUTHORITY.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE CIP_AUTHORITY_MEMBER IS '사용자별 권한들';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.AUTHORITY_ID IS '권한 코드';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.MEMBER_SEQ IS '회원_SEQ';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN CIP_AUTHORITY_MEMBER.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE CIP_COMMON_CODE IS '공통코드';
COMMENT ON COLUMN CIP_COMMON_CODE.COMMON_CODE_ID IS '공통 코드_ID';
COMMENT ON COLUMN CIP_COMMON_CODE.NAME IS '명칭';
COMMENT ON COLUMN CIP_COMMON_CODE.ORDER_NUMBER IS '정렬순서';
COMMENT ON COLUMN CIP_COMMON_CODE.ATTRIBUTION_1 IS '속성_1';
COMMENT ON COLUMN CIP_COMMON_CODE.ATTRIBUTION_2 IS '속성_2';
COMMENT ON COLUMN CIP_COMMON_CODE.DESCRIPTION IS '코드설명';
COMMENT ON COLUMN CIP_COMMON_CODE.SYSTEM_CODE_YN IS '초기 시스템 코드 여부';
COMMENT ON COLUMN CIP_COMMON_CODE.USE_YN IS '사용 여부';
COMMENT ON COLUMN CIP_COMMON_CODE.PARENT_COMMON_CODE_ID IS '상위 공통 코드 ID';
COMMENT ON COLUMN CIP_COMMON_CODE.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN CIP_COMMON_CODE.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN CIP_COMMON_CODE.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN CIP_COMMON_CODE.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE CIP_MEMBER IS '회원정보';
COMMENT ON COLUMN CIP_MEMBER.MEMBER_SEQ IS '회원_SEQ';
COMMENT ON COLUMN CIP_MEMBER.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN CIP_MEMBER.PASSWORD IS '암호';
COMMENT ON COLUMN CIP_MEMBER.CRYPT_PASSWORD IS '암호화된 암호';
COMMENT ON COLUMN CIP_MEMBER.NAME IS '명칭';
COMMENT ON COLUMN CIP_MEMBER.EMAIL IS 'EMAIL';
COMMENT ON COLUMN CIP_MEMBER.CELLPHONE IS '휴대폰번호';
COMMENT ON COLUMN CIP_MEMBER.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN CIP_MEMBER.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN CIP_MEMBER.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN CIP_MEMBER.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN CIP_MEMBER.ORGANIZATION_SEQ IS '조직 일련번호';
COMMENT ON TABLE CIP_MENU IS '메뉴 마스터 정보';
COMMENT ON COLUMN CIP_MENU.MENU_SEQ IS '메뉴 코드 SEQ';
COMMENT ON COLUMN CIP_MENU.NAME IS '명칭';
COMMENT ON COLUMN CIP_MENU.ORDER_NUMBER IS '정렬순서';
COMMENT ON COLUMN CIP_MENU.MENU_URI IS '메뉴 주소';
COMMENT ON COLUMN CIP_MENU.USE_YN IS '사용 여부';
COMMENT ON COLUMN CIP_MENU.PARENT_MENU_SEQ IS '상위 메뉴 코드 SEQ';
COMMENT ON COLUMN CIP_MENU.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN CIP_MENU.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN CIP_MENU.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN CIP_MENU.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE CIP_MENU_AUTHORITY IS '메뉴 따른 권한';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.AUTHORITY_ID IS '권한 코드';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.MENU_SEQ IS '메뉴 코드 SEQ';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN CIP_MENU_AUTHORITY.MODIFY_DATE IS '수정일자';
COMMENT ON TABLE CIP_MULTI_BOARD IS '멀티게시판';
COMMENT ON COLUMN CIP_MULTI_BOARD.MULTI_BOARD_SEQ IS '게시물 일련번호';
COMMENT ON COLUMN CIP_MULTI_BOARD.TITLE IS '제목';
COMMENT ON COLUMN CIP_MULTI_BOARD.CONTENT IS '내용/댓글';
COMMENT ON COLUMN CIP_MULTI_BOARD.START_DATE IS '시작일시 (공지 등)';
COMMENT ON COLUMN CIP_MULTI_BOARD.END_DATE IS '종료일시 (공지 등)';
COMMENT ON COLUMN CIP_MULTI_BOARD.REGISTER_SEQ IS '등록자SEQ';
COMMENT ON COLUMN CIP_MULTI_BOARD.REGISTRY_DATE IS '등록일자';
COMMENT ON COLUMN CIP_MULTI_BOARD.MODIFIER_SEQ IS '수정자_SEQ';
COMMENT ON COLUMN CIP_MULTI_BOARD.MODIFY_DATE IS '수정일자';
COMMENT ON COLUMN CIP_MULTI_BOARD.PARENT_MULTI_BOARD_SEQ IS '상위 게시물 일련번호';
COMMENT ON TABLE CIP_ORGANIZATION IS '그룹/조직/부서 구조도';
COMMENT ON COLUMN CIP_ORGANIZATION.ORGANIZATION_SEQ IS '조직 일련번호';
COMMENT ON COLUMN CIP_ORGANIZATION.NAME IS '명칭';
COMMENT ON COLUMN CIP_ORGANIZATION.TELEPHONE IS '대표 전화번호';
COMMENT ON COLUMN CIP_ORGANIZATION.ORDER_NUMBER IS '정렬순서';
COMMENT ON COLUMN CIP_ORGANIZATION.PARENT_ORGANIZATION_SEQ IS '상위 조직 일련번호';



